on: workflow_dispatch


jobs:
  typesense-scrap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3   # You MUST checkout your repository first!

      - name: Run DocSearch Scraper
        uses: celsiusnarhwal/typesense-scraper@v2
        with:
          # The secret containing your Typesense API key. Required.
          api-key: ${{ secrets.TYPESENSE_API_KEY }}
          
          # The hostname or IP address of your Typesense server. Required.
          host: p4t9rvn51jzwakgep-1.a1.typesense.net
          
          # The port on which your Typesense server is listening. Optional. Default: 8108.
          port: 443
          
          # The protocol to use when connecting to your Typesense server. Optional. Default: http.
          protocol: https
          
          # The path to your DocSearch config file. Optional. Default: docsearch.config.json.
          config: docsearch.config.json